config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root :to => 'books#index'

  resources :users
  resources :histories
  resources :books
  post 'books/take/:id', to: 'books#take', as: 'take_book'
  put 'books/return_book/:id', to: 'books#return_book', as: 'return_book'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/book.rb
class Book
  include Mongoid::Document
  has_many :comments
  belongs_to :user
  field :name, type: String
  field :description, type: String
  field :author, type: String
  field :status, type: Integer, default: 0
  field :user_id, type: String
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :check_rule, only: [:new, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :show]
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def take
    book = Book.find(params[:id])
    history = History.find_by({book_id: params[:id], user_id: current_user.id, returned: nil})
    redirect_back(fallback_location: root_path, notice: 'Book not found.') if book.nil?
    redirect_back(fallback_location: root_path, notice: 'Book is already taken by you.') unless history.nil?
    History.create(user_id: current_user.id, book_id: params[:id], taken: Time.current, returned: '')
    redirect_back fallback_location: root_path, notice: 'Success.'
  end

  def return_book
    history = History.find_by({book_id: params[:id], user_id: current_user.id, returned: nil})
    redirect_back(fallback_location: root_path, notice: 'History not found.') if history.nil?
    history.update(returned: Time.current)
    redirect_back fallback_location: root_path, notice: 'Success.'
  end

  private

  def check_rule
    redirect_to '/', notice: "Увас нет прав на это действие" unless  current_user.role == 'admin'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:name, :description, :author, :status, :user_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_is_taken?(id)
    history = History.find_by({book_id: id, user_id: session[:user_id], returned: nil})
    !history.nil?
  end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>
<%= link_to 'New Book', new_book_path if user_is_admin? %>
<table class="table table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Author</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <th scope="row"><%= book.name %></th>
      <td><%= book.author %></td>
      <td><%= book.status %></td>
        <td>
          <%= link_to 'Show', book %> |
          <% if user_is_admin?  %>
          <%= link_to 'Edit', edit_book_path(book) %> |
          <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
  <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_book_path(@book)  if user_is_admin? %> |
<%= link_to 'Back', books_path %>

<% if user_signed_in? %>
  <% if book_is_taken?(@book.id) %>
    <%= link_to 'Return', return_book_path(@book.id), class: 'btn btn-success', method: 'put' %>
  <% else %>
    <%= link_to 'Take', take_book_path(@book.id), class: 'btn btn-success', method: 'post' %>
  <% end %>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>
<h3>Comments</h3>
<% @book.comments.each do |comments| %>
  <h3><%= comments.user.name %></h3>
  <p><%= comments.text %></p>
<% end %>
<h3>Add comment</h3>
<%= form_with(model: Comment.new, local: true) do |form| %>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <%= hidden_field_tag :book_id, @book.id %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<h3>History:</h3>